version: "3.9"
services:
  client:
    build:
      context: ./dealsdate_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./dealsdate_frontend:/dealsdate_frontend
    image: saujanyawaikar/client:dealsdate
    container_name: client
    command: npm start

  mssql:
    build: ./dealsdate_db
    image: saujanyawaikar/db:dealsdate
    container_name: db
    ports:
      - "1433:1433"

  api:
    image: saujanyawaikar/api:dealsdate
    build:
      context: ./dealsdate_backend
      dockerfile: ./DealsDate_Backend/Dockerfile
    ports:
      - "44306:443"
      - "44307:80"
    environment:
      ASPNETCORE_URLS: "http://+80;https://+443"
      ASPNETCORE_HTTPS_PORT: "44306"
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: 1
      ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS: true
    volumes:
      - ./dealsdate_backend/DealsDate_Backend:/DealsDate_Backend
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    container_name: api
    depends_on:
      - mssql
